# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('level', models.IntegerField(default=1)),
                ('hp', models.IntegerField(default=1000)),
                ('armor', models.IntegerField(default=32)),
                ('acttack', models.IntegerField(default=90)),
                ('gold', models.IntegerField(default=10000)),
                ('image', models.FileField(default='default.jpg', upload_to='images/')),
                ('weapon', models.IntegerField(null=True)),
                ('armour', models.IntegerField(null=True)),
                ('foot', models.IntegerField(null=True)),
            ],
        ),
    ]
