# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 16:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20170612_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', related_query_name='product', to='products.Category'),
        ),
    ]
