# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 17:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20170612_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(choices=[(1, 'Food'), (2, 'Electronic'), (4, 'Motorbike'), (5, 'Cloyhing')], default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', related_query_name='product', to='products.Category'),
        ),
    ]
