# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20170614_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name_vi',
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_vi',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
