# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_auto_20170614_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_vi',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
