# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_auto_20170615_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=200),
        ),
    ]
